import { useMemo, useState } from "react";
import { Card } from "../../components/Card";
import { Button } from "../../components/Button";
import { FieldWrap, SelectInput, TextInput } from "../../components/Field";
import { CIUDADES_DEMO } from "../../../types";
import type { CiudadDemo } from "../../../types";
import { ESTRUCTURA_CIUDAD_DEMO, PARAMETROS_LABORALES_2026 } from "../../../data/price-model-real";
import {
  calculateFinancialScenario,
  loadFinancialModelParams,
  resetFinancialModelParams,
  saveFinancialModelParams,
  type FinancialModelParams,
} from "../../../modules/financial-model";

function pct(v:number){return `${(v*100).toFixed(2)}%`;}
function money(v:number){return new Intl.NumberFormat("es-MX",{style:"currency",currency:"MXN",maximumFractionDigits:2}).format(v);}
function usd(v:number){return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:2}).format(v);}

export function ModeloPricingPage(){
  const [ciudad,setCiudad]=useState<CiudadDemo>("CDMX");
  const [params,setParams]=useState<FinancialModelParams>(()=>loadFinancialModelParams());
  const [salario,setSalario]=useState(13613.33);
  const [posiciones,setPosiciones]=useState(1);
  const [uniforme,setUniforme]=useState(350);
  const [equipo,setEquipo]=useState(590);
  const [vehiculo,setVehiculo]=useState(0);
  const [examenes,setExamenes]=useState(0);
  const [otros,setOtros]=useState(0);

  const estructura=useMemo(()=>ESTRUCTURA_CIUDAD_DEMO.find((x)=>x.ciudad===ciudad),[ciudad]);
  const result=useMemo(()=>calculateFinancialScenario({ciudad,salarioMensual:salario,posiciones,uniformeMensual:uniforme,equipoMensual:equipo,vehiculoMensual:vehiculo,examenesMensual:examenes,otrosDirectosMensual:otros},params),[ciudad,salario,posiciones,uniforme,equipo,vehiculo,examenes,otros,params]);

  function setParam<K extends keyof FinancialModelParams>(key:K,value:number){setParams((p)=>({...p,[key]:value}));}
  function save(){saveFinancialModelParams(params);}
  function reset(){setParams(resetFinancialModelParams());}

  return <div className="space-y-5">
    <div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-lg font-semibold text-ink-900">Modelo Pricing</h2><p className="text-sm text-ink-500">Simulador técnico de Gross Comp + Estructura de Costos + Cost Summary. Los parámetros guardados alimentarán la siguiente etapa del motor de cotizaciones.</p></div><div className="flex gap-2"><Button variant="secondary" onClick={reset}>Restablecer demo</Button><Button onClick={save}>Guardar parámetros</Button></div></div>

    <Card className="p-5"><p className="text-xs font-semibold uppercase tracking-wide text-brand-700">Escenario de prueba</p><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><FieldWrap label="Ciudad operativa"><SelectInput value={ciudad} onChange={(e)=>setCiudad(e.target.value as CiudadDemo)}>{CIUDADES_DEMO.map((c)=><option key={c}>{c}</option>)}</SelectInput></FieldWrap><FieldWrap label="Salario mensual"><TextInput type="number" step="0.01" value={salario} onChange={(e)=>setSalario(Number(e.target.value))}/></FieldWrap><FieldWrap label="Posiciones"><TextInput type="number" min={1} value={posiciones} onChange={(e)=>setPosiciones(Number(e.target.value))}/></FieldWrap><FieldWrap label="Uniforme / posición mes"><TextInput type="number" value={uniforme} onChange={(e)=>setUniforme(Number(e.target.value))}/></FieldWrap><FieldWrap label="Equipo / posición mes"><TextInput type="number" value={equipo} onChange={(e)=>setEquipo(Number(e.target.value))}/></FieldWrap><FieldWrap label="Vehículo / servicio mes"><TextInput type="number" value={vehiculo} onChange={(e)=>setVehiculo(Number(e.target.value))}/></FieldWrap><FieldWrap label="Exámenes / posición mes"><TextInput type="number" value={examenes} onChange={(e)=>setExamenes(Number(e.target.value))}/></FieldWrap><FieldWrap label="Otros directos / servicio mes"><TextInput type="number" value={otros} onChange={(e)=>setOtros(Number(e.target.value))}/></FieldWrap></div></Card>

    <Card className="p-5"><p className="text-xs font-semibold uppercase tracking-wide text-brand-700">Parámetros editables del modelo</p><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><FieldWrap label="Carga social referencia %"><TextInput type="number" step="0.1" value={params.cargaSocialPct*100} onChange={(e)=>setParam("cargaSocialPct",Number(e.target.value)/100)}/></FieldWrap><FieldWrap label="Overhead %"><TextInput type="number" step="0.1" value={params.overheadPct*100} onChange={(e)=>setParam("overheadPct",Number(e.target.value)/100)}/></FieldWrap><FieldWrap label="Indirectos %"><TextInput type="number" step="0.1" value={params.indirectPct*100} onChange={(e)=>setParam("indirectPct",Number(e.target.value)/100)}/></FieldWrap><FieldWrap label="G&A %"><TextInput type="number" step="0.1" value={params.gaPct*100} onChange={(e)=>setParam("gaPct",Number(e.target.value)/100)}/></FieldWrap><FieldWrap label="Financiamiento %"><TextInput type="number" step="0.1" value={params.financingPct*100} onChange={(e)=>setParam("financingPct",Number(e.target.value)/100)}/></FieldWrap><FieldWrap label="Gross Margin objetivo %"><TextInput type="number" step="0.1" value={params.grossMarginPct*100} onChange={(e)=>setParam("grossMarginPct",Number(e.target.value)/100)}/></FieldWrap><FieldWrap label="Tipo de cambio USD/MXN"><TextInput type="number" step="0.01" value={params.fxUsdMxn} onChange={(e)=>setParam("fxUsdMxn",Number(e.target.value))}/></FieldWrap><FieldWrap label="Costo supervisor / mes"><TextInput type="number" value={params.costoSupervisorMensual} onChange={(e)=>setParam("costoSupervisorMensual",Number(e.target.value))}/></FieldWrap><FieldWrap label="Costo coordinador RH / mes"><TextInput type="number" value={params.costoCoordinadorRhMensual} onChange={(e)=>setParam("costoCoordinadorRhMensual",Number(e.target.value))}/></FieldWrap><FieldWrap label="Costo reclutador Sr / mes"><TextInput type="number" value={params.costoReclutadorSrMensual} onChange={(e)=>setParam("costoReclutadorSrMensual",Number(e.target.value))}/></FieldWrap><FieldWrap label="Costo reclutador / mes"><TextInput type="number" value={params.costoReclutadorMensual} onChange={(e)=>setParam("costoReclutadorMensual",Number(e.target.value))}/></FieldWrap></div><p className="mt-3 text-[11px] text-warning-700">Los costos de estructura están inicialmente en cero porque todavía no tenemos un valor soportado por los archivos extraídos. Jorge/Pricing debe capturarlos o validarlos antes de convertirlos en parámetros productivos.</p></Card>

    <div className="grid gap-4 xl:grid-cols-2"><Card className="p-5"><p className="text-xs font-semibold uppercase tracking-wide text-ink-600">Gross Comp · por posición / mes</p><div className="mt-4 overflow-x-auto"><table className="w-full text-sm"><tbody className="divide-y divide-ink-100"><tr><td className="py-2">Sueldo base</td><td className="py-2 text-right font-semibold">{money(result.laboral.sueldo)}</td></tr><tr><td className="py-2">Aguinaldo mensualizado</td><td className="py-2 text-right">{money(result.laboral.aguinaldo)}</td></tr><tr><td className="py-2">Vacaciones mensualizadas</td><td className="py-2 text-right">{money(result.laboral.vacaciones)}</td></tr><tr><td className="py-2">Prima vacacional</td><td className="py-2 text-right">{money(result.laboral.primaVacacional)}</td></tr><tr><td className="py-2">ISN</td><td className="py-2 text-right">{money(result.laboral.isn)}</td></tr><tr><td className="py-2">Riesgo de trabajo</td><td className="py-2 text-right">{money(result.laboral.riesgoTrabajo)}</td></tr><tr><td className="py-2">Otras cargas por desglosar</td><td className="py-2 text-right">{money(result.laboral.otrasCargas)}</td></tr><tr className="font-semibold"><td className="py-2">Costo laboral real de referencia</td><td className="py-2 text-right">{money(result.laboral.totalUnitario)}</td></tr></tbody></table></div><p className="mt-3 text-[11px] text-ink-500">UMA {money(PARAMETROS_LABORALES_2026.umaDiaria)} · vacaciones {PARAMETROS_LABORALES_2026.vacacionesDias} días · prima {pct(PARAMETROS_LABORALES_2026.primaVacacionalPct)} · aguinaldo {PARAMETROS_LABORALES_2026.aguinaldoDias} días.</p></Card>

    <Card className="p-5"><p className="text-xs font-semibold uppercase tracking-wide text-ink-600">Estructura operativa · {ciudad}</p>{estructura?<div className="mt-4 grid grid-cols-2 gap-4 sm:grid-cols-3"><div><small>Región</small><p className="font-semibold">{estructura.region}</p></div><div><small>HC actual</small><p className="font-semibold">{result.estructura.hcActual}</p></div><div><small>HC proyectado</small><p className="font-semibold">{result.estructura.hcProyectado}</p></div><div><small>Sup actuales</small><p className="font-semibold">{result.estructura.supervisoresActuales}</p></div><div><small>Sup requeridos</small><p className="font-semibold">{result.estructura.supervisoresRequeridos}</p></div><div><small>Sup adicionales</small><p className="font-semibold">{result.estructura.supervisoresAdicionales}</p></div><div><small>Reclutadores actuales</small><p className="font-semibold">{result.estructura.reclutadoresActuales}</p></div><div><small>Reclutadores requeridos</small><p className="font-semibold">{result.estructura.reclutadoresRequeridos}</p></div><div><small>Rotación operativa</small><p className="font-semibold">{pct(estructura.rotacionPct)}</p></div></div>:null}{result.estructura.requiereCostoPendiente&&<div className="mt-4 rounded-lg border border-warning-200 bg-warning-50 p-3 text-xs text-warning-800">La estructura proyectada requiere personal adicional, pero su costo está en $0. Debe validarse antes de usar este escenario como precio definitivo.</div>}</Card></div>

    <Card className="p-5"><p className="text-xs font-semibold uppercase tracking-wide text-brand-700">Cost Summary · mensual / anual</p><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="bg-ink-50 text-xs uppercase text-ink-500"><tr><th className="px-3 py-2 text-left">Concepto</th><th className="px-3 py-2 text-right">Mensual</th><th className="px-3 py-2 text-right">Anual</th></tr></thead><tbody className="divide-y divide-ink-100">{[["Costo laboral",result.costos.labor],["Uniformes",result.costos.uniforme],["Equipamiento",result.costos.equipo],["Vehículos",result.costos.vehiculo],["Exámenes",result.costos.examenes],["Otros directos",result.costos.otrosDirectos],["Estructura adicional",result.costos.estructura],["Overhead",result.costos.overhead],["Indirectos",result.costos.indirectos],["G&A",result.costos.ga],["Financiamiento",result.costos.financiamiento]].map(([label,value])=><tr key={String(label)}><td className="px-3 py-2">{label}</td><td className="px-3 py-2 text-right">{money(Number(value))}</td><td className="px-3 py-2 text-right">{money(Number(value)*12)}</td></tr>)}<tr className="bg-ink-50 font-semibold"><td className="px-3 py-2">Costo real IC</td><td className="px-3 py-2 text-right">{money(result.costos.costoTotalMensual)}</td><td className="px-3 py-2 text-right">{money(result.costos.costoTotalAnual)}</td></tr><tr className="bg-brand-50 font-semibold text-brand-800"><td className="px-3 py-2">Precio final recomendado · GM {pct(result.precio.gm)}</td><td className="px-3 py-2 text-right">{money(result.precio.mensualMxn)}</td><td className="px-3 py-2 text-right">{money(result.precio.anualMxn)}</td></tr><tr><td className="px-3 py-2">Equivalente USD · FX {params.fxUsdMxn}</td><td className="px-3 py-2 text-right">{usd(result.precio.mensualUsd)}</td><td className="px-3 py-2 text-right">{usd(result.precio.anualUsd)}</td></tr></tbody></table></div></Card>

    <Card className="p-5"><p className="text-xs font-semibold uppercase tracking-wide text-warning-700">Estado de paridad con Excel</p><div className="mt-3 grid gap-3 sm:grid-cols-3"><div className="rounded-lg border border-success-200 bg-success-50 p-3"><p className="text-sm font-semibold">Gross Comp base</p><p className="mt-1 text-xs">Sueldo, aguinaldo, vacaciones, prima, ISN y riesgo ya están separados.</p></div><div className="rounded-lg border border-warning-200 bg-warning-50 p-3"><p className="text-sm font-semibold">Cargas IMSS/INFONAVIT</p><p className="mt-1 text-xs">Siguen agrupadas en “otras cargas” hasta terminar el desmontaje fino de Gross Comp.</p></div><div className="rounded-lg border border-warning-200 bg-warning-50 p-3"><p className="text-sm font-semibold">Indirectos / G&A / financiamiento</p><p className="mt-1 text-xs">Ya son editables y calculables, pero falta confirmar sus fórmulas exactas contra Estructura de Costos y Cash Flow.</p></div></div></Card>
  </div>;
}
